# Generated by Django 6.0 on 2025-12-29 17:15

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConnectionProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('db_type', models.CharField(choices=[('postgres', 'PostgreSQL'), ('mongodb', 'MongoDB'), ('chromadb', 'ChromaDB'), ('weaviate', 'Weaviate'), ('milvus', 'Milvus')], max_length=50)),
                ('credentials', models.JSONField(help_text='JSON containing host, port, etc.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
