# Generated by Django 6.0 on 2025-12-30 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explorer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='connectionprofile',
            name='encrypted_credentials',
            field=models.TextField(blank=True, help_text='Encrypted credentials string', null=True),
        ),
        migrations.AddField(
            model_name='connectionprofile',
            name='schema_metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Cached schema information'),
        ),
        migrations.AlterField(
            model_name='connectionprofile',
            name='credentials',
            field=models.JSONField(blank=True, help_text='JSON containing host, port, etc.', null=True),
        ),
    ]
