# Generated by Django 6.0 on 2025-12-30 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explorer', '0003_connectionprofile_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='connectionprofile',
            name='credentials',
        ),
        migrations.RemoveField(
            model_name='connectionprofile',
            name='user',
        ),
        migrations.AddField(
            model_name='connectionprofile',
            name='session_id',
            field=models.CharField(blank=True, db_index=True, help_text='Django Session Key', max_length=40, null=True),
        ),
    ]
