# Generated by Django 6.0 on 2025-12-30 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explorer', '0004_remove_connectionprofile_credentials_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelemetryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(db_index=True, max_length=40)),
                ('db_type', models.CharField(max_length=20)),
                ('table_count', models.IntegerField(default=0)),
                ('data_volume_mb', models.FloatField(default=0.0, help_text='Size in MB')),
                ('device_os', models.CharField(blank=True, max_length=50, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
