# Generated by Django 6.0 on 2025-12-30 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explorer', '0005_telemetrylog'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(db_index=True, max_length=40)),
                ('name', models.CharField(max_length=100)),
                ('sql', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
