# Generated by Django 6.0 on 2025-12-30 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explorer', '0006_savedquery'),
    ]

    operations = [
        migrations.AddField(
            model_name='telemetrylog',
            name='connection_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='telemetrylog',
            name='query_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='telemetrylog',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
